/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.100
 * Generated at: 2026-06-19 07:17:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.auth;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Jang_adam/AI_Full_stack/track005_jsp/apache-tomcat-9.0.100/wtpwebapps/spring-breeze-erp-v1/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1780553367131L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Jang_adam/AI_Full_stack/track005_jsp/apache-tomcat-9.0.100/wtpwebapps/spring-breeze-erp-v1/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"_csrf\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<meta name=\"_csrf_header\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.headerName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<title>로그인 · SBerp</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/pretendard@1.3.9/dist/web/static/pretendard.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/app.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/auth.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"login-page\">\r\n");
      out.write("	<div class=\"aw\">\r\n");
      out.write("		<!-- 왼쪽 브랜드 패널 -->\r\n");
      out.write("		<aside class=\"ab\">\r\n");
      out.write("			<div class=\"ab-logo\">\r\n");
      out.write("				<div class=\"ab-mark\">S</div>\r\n");
      out.write("				<span class=\"ab-name\">SBerp</span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"ab-mid\">\r\n");
      out.write("				<div class=\"ab-tagline\">전사 통합 ERP,<br>하나의 플랫폼으로</div>\r\n");
      out.write("				<div class=\"ab-tagline-sub\">인사·조직 관리부터 전자문서 결재,<br>프로젝트·자원예약까지 모두 한 곳에서</div>\r\n");
      out.write("				<div class=\"ab-feats\">\r\n");
      out.write("					<div class=\"ab-feat\">\r\n");
      out.write("						<i class=\"bi bi-file-earmark-check-fill\"></i><span>전자문서 · 결재 관리</span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"ab-feat\">\r\n");
      out.write("						<i class=\"bi bi-people-fill\"></i><span>인사 · 조직 · 권한 관리</span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"ab-feat\">\r\n");
      out.write("						<i class=\"bi bi-kanban-fill\"></i><span>프로젝트 · 태스크 관리</span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"ab-feat\">\r\n");
      out.write("						<i class=\"bi bi-calendar2-check-fill\"></i><span>자원 · 공간 예약관리</span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"ab-foot\">© 2026 SBerp · All rights reserved.</div>\r\n");
      out.write("		</aside>\r\n");
      out.write("		<!-- 왼쪽 브랜드 패널 -->\r\n");
      out.write("\r\n");
      out.write("		<!-- 오른쪽 로그인 폼 -->\r\n");
      out.write("		<main class=\"ap\">\r\n");
      out.write("			<div class=\"ap-wrap\">\r\n");
      out.write("				<!-- section: 로그인 -->\r\n");
      out.write("				<div class=\"asec on\" id=\"secLogin\">\r\n");
      out.write("					<h1 class=\"a-h\">안녕하세요 👋</h1>\r\n");
      out.write("					<p class=\"a-sub\">이메일과 비밀번호를 입력하여<br>SBerp에 로그인하세요.</p>\r\n");
      out.write("					<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/auth/login\" method=\"post\" id=\"fmLogin\" novalidate autocomplete=\"on\">\r\n");
      out.write("						<input  type=\"hidden\" name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("						<label class=\"fl\" for=\"iEmail\">이메일 주소</label>\r\n");
      out.write("						<div class=\"fw\">\r\n");
      out.write("							<input class=\"fi ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty param.error ? 'er' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" type=\"email\" id=\"iEmail\"\r\n");
      out.write("								placeholder=\"name@smartbuilder.com\" name=\"username\"\r\n");
      out.write("								value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty param.error ? sessionScope.SPRING_SECURITY_LAST_USERNAME : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("								autocomplete=\"email\" spellcheck=\"false\">\r\n");
      out.write("							<i class=\"bi bi-envelope f-icon\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"fe\" id=\"eEmail\">\r\n");
      out.write("							<i class=\"bi bi-exclamation-circle\"></i><span></span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div style=\"display: flex; justify-content: space-between; align-items: center; margin-bottom: 7px\">\r\n");
      out.write("							<label class=\"fl\" for=\"iPw\" style=\"margin: 0\">비밀번호</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"fw\">\r\n");
      out.write("							<input class=\"fi ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty param.error ? 'er' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" type=\"password\" id=\"iPw\"\r\n");
      out.write("								placeholder=\"비밀번호 입력\" name=\"password\" autocomplete=\"current-password\">\r\n");
      out.write("								<i class=\"bi bi-eye f-icon clickable\" id=\"togglePw\" title=\"표시/숨기기\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"fe\" id=\"ePw\">\r\n");
      out.write("							<i class=\"bi bi-exclamation-circle\"></i><span></span>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- <label style=\"display:flex;align-items:center;gap:8px;margin-bottom:22px;cursor:pointer\">\r\n");
      out.write("		            <input type=\"checkbox\" style=\"width:15px;height:15px;accent-color:var(--sb-accent)\">\r\n");
      out.write("		            <span style=\"font-size:13.5px;color:var(--sb-ink-soft)\">로그인 상태 유지</span>\r\n");
      out.write("		          </label> -->\r\n");
      out.write("\r\n");
      out.write("						");
      out.write("\r\n");
      out.write("						<div class=\"a-alert ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty param.error ? 'on' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"alertLogin\">\r\n");
      out.write("							<i class=\"bi bi-exclamation-triangle-fill\"></i> <span\r\n");
      out.write("								id=\"alertLoginTxt\">");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("</span>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("  					    <button type=\"button\" class=\"a-link\" id=\"toForgot\">비밀번호를 잊으셨나요?</button>\r\n");
      out.write("						<button type=\"submit\" class=\"a-btn\" id=\"btnLogin\">\r\n");
      out.write("							<i class=\"bi bi-box-arrow-in-right\"></i><span>로그인</span>\r\n");
      out.write("						</button>\r\n");
      out.write("					</form>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"a-demo\">\r\n");
      out.write("						<p>\r\n");
      out.write("							<i class=\"bi bi-info-circle\"></i> 데모 계정<br> \r\n");
      out.write("							이메일 <code>shin.yn@springbreeze.co.kr</code>\r\n");
      out.write("						  / 비밀번호 <code>1234</code>\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- section: 비밀번호 찾기 -->\r\n");
      out.write("				<div class=\"asec\" id=\"secForgot\">\r\n");
      out.write("					<button type=\"button\" class=\"a-back\" id=\"backToLogin\">\r\n");
      out.write("						<i class=\"bi bi-arrow-left\"></i> 로그인으로 돌아가기\r\n");
      out.write("					</button>\r\n");
      out.write("					<h1 class=\"a-h\">비밀번호 찾기</h1>\r\n");
      out.write("					<p class=\"a-sub\">\r\n");
      out.write("						사원번호 · 이메일 · 휴대폰 번호가<br>등록된 정보와 일치하면 재설정 페이지로 이동합니다.\r\n");
      out.write("					</p>\r\n");
      out.write("\r\n");
      out.write("					<form id=\"fmForgot\" novalidate>\r\n");
      out.write("						<label class=\"fl\" for=\"empNo\">사원번호</label>\r\n");
      out.write("						<div class=\"fw\">\r\n");
      out.write("							<input class=\"fi\" type=\"text\" id=\"empNo\" placeholder=\"E1001\"\r\n");
      out.write("								spellcheck=\"false\" name=\"empNo\" autocapitalize=\"characters\">\r\n");
      out.write("							<i class=\"bi bi-person f-icon\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<label class=\"fl\" for=\"empEmail\">이메일 주소</label>\r\n");
      out.write("						<div class=\"fw\">\r\n");
      out.write("							<input class=\"fi\" type=\"email\" id=\"empEmail\"\r\n");
      out.write("								placeholder=\"name@sberp.co.kr\" name=\"empEmail\"> <i\r\n");
      out.write("								class=\"bi bi-envelope f-icon\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<label class=\"fl\" for=\"empMobile\">휴대폰 번호</label>\r\n");
      out.write("						<div class=\"fw\">\r\n");
      out.write("							<input class=\"fi\" type=\"tel\" id=\"empMobile\" name=\"empMobile\"\r\n");
      out.write("								placeholder=\"010-0000-0000\"> <i\r\n");
      out.write("								class=\"bi bi-phone f-icon\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"a-alert\" id=\"alertForgot\">\r\n");
      out.write("							<i class=\"bi bi-exclamation-triangle-fill\"></i> <span\r\n");
      out.write("								id=\"alertForgotTxt\"></span>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<button type=\"submit\" class=\"a-btn\" id=\"btnForgot\">\r\n");
      out.write("							<i class=\"bi bi-shield-check\"></i><span>본인 확인</span>\r\n");
      out.write("						</button>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</main>\r\n");
      out.write("	</div>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("(function () {\r\n");
      out.write("  'use strict';\r\n");
      out.write("\r\n");
      out.write("  /* ---- 유틸 ---- */\r\n");
      out.write("  function fe(id, msg) {\r\n");
      out.write("    var el = document.getElementById(id);\r\n");
      out.write("    el.querySelector('span').textContent = msg || '';\r\n");
      out.write("    el.classList.toggle('on', !!msg);\r\n");
      out.write("  }\r\n");
      out.write("  function fi(id, hasErr) { document.getElementById(id).classList.toggle('er', !!hasErr); }\r\n");
      out.write("  function alert_(alertId, txtId, msg) {\r\n");
      out.write("    document.getElementById(txtId).textContent = msg || '';\r\n");
      out.write("    document.getElementById(alertId).classList.toggle('on', !!msg);\r\n");
      out.write("  }\r\n");
      out.write("  function loading(btn, on, icon, label) {\r\n");
      out.write("    btn.disabled = on;\r\n");
      out.write("    btn.innerHTML = on\r\n");
      out.write("      ? '<span class=\"spinner-border spinner-border-sm\" style=\"width:16px;height:16px\"></span><span>확인 중…</span>'\r\n");
      out.write("      : '<i class=\"' + icon + '\"></i><span>' + label + '</span>';\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  /* ---- 섹션 전환 ---- */\r\n");
      out.write("  document.getElementById('toForgot').addEventListener('click', function () {\r\n");
      out.write("    document.getElementById('secLogin').classList.remove('on');\r\n");
      out.write("    document.getElementById('secForgot').classList.add('on');\r\n");
      out.write("    document.getElementById('empNo').focus();\r\n");
      out.write("  });\r\n");
      out.write("  document.getElementById('backToLogin').addEventListener('click', function () {\r\n");
      out.write("    document.getElementById('secForgot').classList.remove('on');\r\n");
      out.write("    document.getElementById('secLogin').classList.add('on');\r\n");
      out.write("    document.getElementById('iEmail').focus();\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("  /* ---- 비밀번호 표시/숨기기 ---- */\r\n");
      out.write("  document.getElementById('togglePw').addEventListener('click', function () {\r\n");
      out.write("    let inp = document.getElementById('iPw');\r\n");
      out.write("    let show = inp.type === 'password';\r\n");
      out.write("    inp.type = show ? 'text' : 'password';\r\n");
      out.write("    this.className = (show ? 'bi bi-eye-slash' : 'bi bi-eye') + ' f-icon clickable';\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("  /* ---- 로그인 폼 ----\r\n");
      out.write("     실제 인증은 서버(Spring Security /auth/login)에서 처리하는 일반 폼 제출입니다.\r\n");
      out.write("     여기서는 빈 값 클라이언트 검증만 하고, 통과하면 그대로 서버로 제출합니다\r\n");
      out.write("     (e.preventDefault를 호출하지 않음 → 실제 로그인 처리/리다이렉트가 정상 동작). */\r\n");
      out.write("  document.getElementById('fmLogin').addEventListener('submit', function (e) {\r\n");
      out.write("    var email = document.getElementById('iEmail').value.trim();\r\n");
      out.write("    var pw    = document.getElementById('iPw').value;\r\n");
      out.write("    var ok = true;\r\n");
      out.write("\r\n");
      out.write("    fe('eEmail', ''); fi('iEmail', false);\r\n");
      out.write("    fe('ePw', '');    fi('iPw', false);\r\n");
      out.write("\r\n");
      out.write("    if (!email) { fe('eEmail', '이메일을 입력하세요.'); fi('iEmail', true); ok = false; }\r\n");
      out.write("    if (!pw)    { fe('ePw', '비밀번호를 입력하세요.'); fi('iPw', true); ok = false; }\r\n");
      out.write("\r\n");
      out.write("    if (!ok) { e.preventDefault(); return; }\r\n");
      out.write("\r\n");
      out.write("    loading(document.getElementById('btnLogin'), true);\r\n");
      out.write("    /* 서버 응답(리다이렉트) 전까지 버튼은 로딩 상태 유지, 실패 시 페이지가\r\n");
      out.write("       /auth/login?error=true 로 다시 로드되면서 버튼/필드는 자동으로 초기 상태로 복원됨 */\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("  ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("  /* ---- 비밀번호 찾기 폼 ---- */\r\n");
      out.write("  document.getElementById('fmForgot').addEventListener('submit', function (e) {\r\n");
      out.write("    e.preventDefault();\r\n");
      out.write("    let no     = document.getElementById('empNo').value.trim();\r\n");
      out.write("    let email  = document.getElementById('empEmail').value.trim();\r\n");
      out.write("    let mobile = document.getElementById('empMobile').value.trim();\r\n");
      out.write("\r\n");
      out.write("    alert_('alertForgot', 'alertForgotTxt', '');\r\n");
      out.write("    if (!no || !email || !mobile) {\r\n");
      out.write("      alert_('alertForgot', 'alertForgotTxt', '모든 항목을 빠짐없이 입력해 주세요.');\r\n");
      out.write("      return;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    let btn = document.getElementById('btnForgot');\r\n");
      out.write("    loading(btn, true);\r\n");
      out.write("    \r\n");
      out.write("    var csrfToken  = document.querySelector('meta[name=\"_csrf\"]').content;\r\n");
      out.write("    var csrfHeader = document.querySelector('meta[name=\"_csrf_header\"]').content;\r\n");
      out.write("    \r\n");
      out.write("    let headers = { 'Content-Type': 'application/x-www-form-urlencoded' };\r\n");
      out.write("    headers[csrfHeader] = csrfToken;\r\n");
      out.write("\r\n");
      out.write("    fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/auth/confirm', {\r\n");
      out.write("      method: 'POST',\r\n");
      out.write("      headers: headers,\r\n");
      out.write("      body: new URLSearchParams({ empNo: no, empEmail: email, empMobile: mobile })\r\n");
      out.write("    })\r\n");
      out.write("      .then(function (res) { return res.json(); })\r\n");
      out.write("      .then(function (data) {\r\n");
      out.write("        if (data.state != \"OK\") {\r\n");
      out.write("          loading(btn, false, 'bi bi-shield-check', '본인 확인');\r\n");
      out.write("          alert_('alertForgot', 'alertForgotTxt', '입력하신 정보와 일치하는 계정을 찾을 수 없습니다. 다시 확인해 주세요.');\r\n");
      out.write("          return;\r\n");
      out.write("        }\r\n");
      out.write("        location.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/auth/forgotResetPass';\r\n");
      out.write("      })\r\n");
      out.write("      .catch(function () {\r\n");
      out.write("        loading(btn, false, 'bi bi-shield-check', '본인 확인');\r\n");
      out.write("        alert_('alertForgot', 'alertForgotTxt', '서버와 통신 중 오류가 발생했습니다. 잠시 후 다시 시도해 주세요.');\r\n");
      out.write("      });\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("  /* ---- 휴대폰 자동 하이픈 ---- */\r\n");
      out.write("  document.getElementById('empMobile').addEventListener('input', function () {\r\n");
      out.write("	let v = this.value.replace(/\\D/g, '').slice(0, 11);\r\n");
      out.write("    if (v.length > 7)      v = v.slice(0,3) + '-' + v.slice(3,7) + '-' + v.slice(7);\r\n");
      out.write("    else if (v.length > 3) v = v.slice(0,3) + '-' + v.slice(3);\r\n");
      out.write("    this.value = v;\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("})();\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /view/auth/login.jsp(88,27) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty param.error}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("이메일 또는 비밀번호가 올바르지 않습니다.");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /view/auth/login.jsp(216,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty param.error}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("  /* 로그인 실패로 되돌아온 경우 비밀번호 입력칸에 포커스 */\r\n");
        out.write("  document.getElementById('iPw').focus();\r\n");
        out.write("  ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }
}
