/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.100
 * Generated at: 2026-05-21 08:39:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.*;

public final class jsp013_005fimplicait_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang = \"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title> JSP </title>\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("	<body>\r\n");
      out.write("	<!-- jsp013_implicit.jsp -->\r\n");
      out.write("		<div class=\" p-5 bg-primary text-white \">\r\n");
      out.write("			<h3 class=\"card-header\">001. 내장객체</h3> 	\r\n");
      out.write("				<pre>\r\n");
      out.write("				1. jsp 페이지가 웹컨테이너에 의해 \r\n");
      out.write("				2. 고정된 이름의 객체 컨테이너를 자동으로 구현\r\n");
      out.write("				3. request(요청), response(응답), session(정보저장), out(출력)\r\n");
      out.write("				</pre>\r\n");
      out.write("				\r\n");
      out.write("				<h4>002. request - getParameter</h4>\r\n");
      out.write("				<pre>\r\n");
      out.write("				1. 처리해주는 해결사 : action = \"jsp013_1.jsp\"\r\n");
      out.write("				2. 요청방식		 : 주소표시창 노출\r\n");
      out.write("				3. 보관용기기름 	 : query\r\n");
      out.write("									=getParameter(\"name\")\r\n");
      out.write("				4. 출력내용		 :\r\n");
      out.write("					검색어 : 입력값 \r\n");
      out.write("				</pre>\r\n");
      out.write("				<form action=\"jsp013_1.jsp\" method=\"get\" onsubmit=\"return check()\">\r\n");
      out.write("				  <div class=\"my-2\">\r\n");
      out.write("				     <label for=\"query\">검색어</label> \r\n");
      out.write("				     <input type=\"text\" class=\"form-control\" placeholder=\"\" id=\"query\" name=\"query\" />\r\n");
      out.write("				     <button type=\"submit\" class=\"btn btn-success mt-3 d-block\">검색</button>\r\n");
      out.write("				  </div>\r\n");
      out.write("				</form>\r\n");
      out.write("				<br/><!-- 줄바꿈 -->\r\n");
      out.write("				<br/><!-- 줄바꿈 -->\r\n");
      out.write("				\r\n");
      out.write("				<!-- 			 -->\r\n");
      out.write("				<!-- 			 -->\r\n");
      out.write("				<!-- 			 -->\r\n");
      out.write("				<br/>\r\n");
      out.write("			      <pre>\r\n");
      out.write("			      1. 처리해주는 해결사 : action=\"jsp013_2.jsp\"\r\n");
      out.write("			      2. 요청방식        : 주소표시창 노출\r\n");
      out.write("			      3. 보관용기이름     :  username / checkbox: option1\r\n");
      out.write("			      = getParameterVaulues(\"name\")\r\n");
      out.write("			      4. 출력내용 :  \r\n");
      out.write("			      검색어 : 입력한값\r\n");
      out.write("			      </pre>\r\n");
      out.write("			      <form action=\"jsp013_2.jsp\"  method=\"get\"  onsubmit=\"return checkbox()\"  >\r\n");
      out.write("			        <div class=\"mb-3 mt-3\">\r\n");
      out.write("			          <label for=\"username\" class=\"form-label\">NAME:</label> \r\n");
      out.write("			          <input  type=\"text\" class=\"form-control\" id=\"username\"\r\n");
      out.write("			               placeholder=\"Enter email\" name=\"username\">\r\n");
      out.write("			         </div><!-- user name -->\r\n");
      out.write("			         <div class=\"form-check\">\r\n");
      out.write("			           <input class=\"form-check-input\" type=\"checkbox\" \r\n");
      out.write("			                  id=\"check1\" name=\"option1\" value=\"dog\" >\r\n");
      out.write("			           <label class=\"form-check-label\" for=\"check1\">DOG</label>\r\n");
      out.write("			         </div>\r\n");
      out.write("			         <div class=\"form-check\">\r\n");
      out.write("			           <input class=\"form-check-input\" type=\"checkbox\" \r\n");
      out.write("			                  id=\"check2\" name=\"option1\" value=\"cat\" >\r\n");
      out.write("			           <label class=\"form-check-label\"  for=\"check2\" >CAT</label>\r\n");
      out.write("			         </div>   \r\n");
      out.write("			         <div class=\"form-check\">\r\n");
      out.write("			           <input class=\"form-check-input\" type=\"checkbox\" \r\n");
      out.write("			                  id=\"check3\" name=\"option1\" value=\"pig\"   >\r\n");
      out.write("			           <label class=\"form-check-label\"  for=\"check3\">PIG</label>\r\n");
      out.write("			         </div>\r\n");
      out.write("			         <div class=\"my-3\">\r\n");
      out.write("			              <button  type=\"submit\"  class=\"btn btn-success mt-3 d-block\" >전송</button>\r\n");
      out.write("			         </div>                  \r\n");
      out.write("			      </form>\r\n");
      out.write("				\r\n");
      out.write("				<hr/>		\r\n");
      out.write("				<h4>003. response</h4>\r\n");
      out.write("				<pre class=\"alert alert-info\">\r\n");
      out.write("				1. http 요청에 대한 응답저장 하는 객체\r\n");
      out.write("				2. jsp에서 다른페이지로 이동\r\n");
      out.write("					(1) sendRedirect      - 브라우저 url을 변경o, request/response 객체가 유지 안됨\r\n");
      out.write("					(2) RequestDispatcher - 위임 (요청전달)          \r\n");
      out.write("											브라우저 url을 변경x, request/response 객체가 유지 안됨\r\n");
      out.write("				</pre>\r\n");
      out.write("				");

				//ver-1  알림창 처리가 안됨.
				////out.println("<script> alert('안녕'); </script>");	//알림창x
				//response.sendRedirect("http://www.naver.com");		
				
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				");

				//var-2.    
				//jsp013_3.jsp
				//request.getRequestDispatcher("jsp012_milks.jsp").forward(request, response); 이용해서 여기서 처리해줘
				//response.sendRedirect("jsp013_3.jsp");
				
      out.write("\r\n");
      out.write("				<pre class=\"alert alert-success\">\r\n");
      out.write("				      jsp013_implicit.jsp (1)→ \r\n");
      out.write("				      :나이 입력받는폼 \r\n");
      out.write("				      \r\n");
      out.write("					     	 jsp013_4.jsp  처리 (2)→ \r\n");
      out.write("					     	    \r\n");
      out.write("		                          19세 미만이라면 -  jsp013_child.jsp\r\n");
      out.write("		                          19세 이상이라면 -  보여주는 주소표시창줄은   jsp013_4.jsp  \r\n");
      out.write("		                                 		 보이는화면은   jsp013_adult.jsp\r\n");
      out.write("				</pre>\r\n");
      out.write("				\r\n");
      out.write("				<form action=\"jsp013_4.jsp\" method=\"get\" onsubmit=\"return check()\">\r\n");
      out.write("				  <div class=\"my-2\">\r\n");
      out.write("				     <label for=\"userage\">성인검색</label> \r\n");
      out.write("				     <input type=\"text\" class=\"form-control\" placeholder=\"\" id=\"userage\" name=\"userage\" />\r\n");
      out.write("				     <button type=\"submit\" class=\"btn btn-success mt-3 d-block\">성인여부</button>\r\n");
      out.write("				  </div>\r\n");
      out.write("				</form>\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				<hr/>\r\n");
      out.write("				<h4>004. scope</h4>\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				<hr/>\r\n");
      out.write("				<h4>004. error</h4>\r\n");
      out.write("			\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("		</div>\r\n");
      out.write("	</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("-->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
