/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.100
 * Generated at: 2026-05-19 08:53:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.*;

public final class Milks_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang = \"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>MILK ORDER Project</title>\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!--   header -->\r\n");
      out.write("<!--   header -->\r\n");
      out.write("<!-- bg-primary(파랑) bg-danger(빨강) wrning(노랑) -->\r\n");
      out.write("<div class=\" p-5 bg-primary text-white \">\r\n");
      out.write("  <h1>Milk Order Project</h1>\r\n");
      out.write("  	<p>MVC1 - PreparedStatement Ex</p>\r\n");
      out.write("  		\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!--   메뉴판테이블 -->	\r\n");
      out.write("<!--   메뉴판테이블 -->\r\n");
      out.write("	<div class=\"container card my-5 bg-primary text-white\">\r\n");
      out.write("		<h2 class=\"card-header\">Milk Menu</h2>\r\n");
      out.write("		<table class=\"table table-bordered table-striped table-hover\">\r\n");
      out.write("  			<caption>우유메뉴</caption>\r\n");
      out.write("  			<thead>\r\n");
      out.write("  				<tr>\r\n");
      out.write("  					<th scope=\"col\">NO</th>\r\n");
      out.write("  						<li>NO.1</li>\r\n");
      out.write("  					<th scope=\"col\">MENU</th>\r\n");
      out.write("  					<th scope=\"col\">PRICE</th>\r\n");
      out.write("  				</tr>\r\n");
      out.write("  			</thead>\r\n");
      out.write("  			<tbody>\r\n");
      out.write("  			");

  			try{
  				
  				//1. 드라이버로딩  필요한 코드?	Class.forName - com.mysql.cj.jdbc.Driver
  					Class.forName("com.mysql.cj.jdbc.Driver");
  					Connection conn=null; PreparedStatement pstmt = null; ResultSet rset = null;
  				//2. JDBC 연동   필요한 코드?	DriverManager.getConnection() - jdbc:mysql://localhost:3306/mbasic
  					 conn = DriverManager.getConnection(
  							 "jdbc:mysql://localhost:3306/mbasic", 
  							 "root", 
  							 "1234");
  	  			//3. PreparedStatement pstmt 이용해서 milk 테이블의 데이터 가져오기 - 가격낮은순으로
  	  				pstmt = conn.prepareStatement("select * from milk order by mprice asc");
  	  				
  	  				rset = pstmt.executeQuery();
  	  				while(rset.next()){
  	  					out.println("<tr><td>"
  	  							+rset.getInt("mno")+"</td><td>"
  	  							+rset.getString("mname")+"</td><td>"
  	  							+rset.getInt("mprice")+"</td></tr>"
  	  							);	
  	  				}
  	  				
  				//4. JDBC 끊기   필요한 코드?	conn.close()
  	  			if(pstmt != null){  pstmt.close();    }   
  	  			if(conn  != null){  conn.close();     }      
  	  			}catch(Exception e){e.printStackTrace();}
  			/*
  			
  			
  			alter table milk modify mnum int null;
  			alter table milk modify mtotal int null;
  			
  			
  			*/
  			
      out.write("\r\n");
      out.write("  			</tbody>\r\n");
      out.write("  		</table>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("<!--   주문현황표 -->	\r\n");
      out.write("<!--   주문현황표 -->	\r\n");
      out.write("<div class=\"container card my-5 bg-primary text-white\">\r\n");
      out.write("		<h2 class=\"card-header\">Menu Order</h2>\r\n");
      out.write("		<table class=\"table table-bordered table-striped table-hover\">\r\n");
      out.write("  			<caption></caption>\r\n");
      out.write("  			<thead>\r\n");
      out.write("  				<tr>\r\n");
      out.write("  					<th scope=\"col\">NO</th>\r\n");
      out.write("  					<th scope=\"col\">NAME</th>\r\n");
      out.write("  					<th scope=\"col\">NUM</th>\r\n");
      out.write("  					<th scope=\"col\">주문날짜</th>\r\n");
      out.write("  				</tr>\r\n");
      out.write("  			</thead>\r\n");
      out.write("  		</table>\r\n");
      out.write("</div>\r\n");
      out.write("<!--   주문삽입, 수정, 삭제 -->	\r\n");
      out.write("<!--   주문삽입, 수정, 삭제 -->		\r\n");
      out.write("<div class=\"container card my-5 bg-primary text-white\">	\r\n");
      out.write("	<h2 class=\"card-header\">Milk 주문하러 가기</h2>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
