/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.100
 * Generated at: 2026-06-19 08:42:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.appr;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Jang_adam/AI_Full_stack/track005_jsp/apache-tomcat-9.0.100/wtpwebapps/spring-breeze-erp-v1/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1780553367131L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("   \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Join</title>\r\n");
      out.write("    <!-- Latest compiled and minified CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Latest compiled JavaScript -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <link href=\"./css/board.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("		<button type=\"button\" class=\"btn btn-primary\"\r\n");
      out.write("			 	onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/appr/write_form'\">양식 등록</button>\r\n");
      out.write("	<div class=\"container my-5 card\">\r\n");
      out.write("	<h3>결재 양식 목록</h3>\r\n");
      out.write("		<form action=\"#\" method=\"post\" onsubmit=\"return checkForm()\">\r\n");
      out.write("		<input type=\"hidden\" name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("		\r\n");
      out.write("			<div class=\"my-3\">\r\n");
      out.write("				<label for=\"keyword\" class=\"form-label\">양식이름, 양식코드</label>\r\n");
      out.write("				<input type=\"text\" class=\"form-control\" id=\"keyword\" name=\"keyword\" />\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"my-3 position-relative\">	\r\n");
      out.write("				<label for=\"companySearch\" class=\"form-label\">회사</label>\r\n");
      out.write("				<input type=\"text\" class=\"form-control\" id=\"companySearch\"\r\n");
      out.write("					   placeholder=\"회사이름 입력\" autocomplete=\"off\"/>\r\n");
      out.write("				\r\n");
      out.write("				<input type=\"hidden\" id=\"comId\" name=\"comId\" />	\r\n");
      out.write("				\r\n");
      out.write("				<div id=\"companyDropdown\" class=\"dropdown-menu w-100\"\r\n");
      out.write("					 style=\"display: none; max-height: 200px; overflow-y: auto;\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("		\r\n");
      out.write("			\r\n");
      out.write("			<script>\r\n");
      out.write("				///////////////////// 회사 이름이랑 일치하는거 출력 /////////////////////\r\n");
      out.write("				window.addEventListener(\"load\", function(){\r\n");
      out.write("					\r\n");
      out.write("					let companySearch = document.getElementById(\"companySearch\");\r\n");
      out.write("					let comId = document.getElementById(\"comId\");\r\n");
      out.write("					let companyDropdown = document.getElementById(\"companyDropdown\");\r\n");
      out.write("					\r\n");
      out.write("					// 입력 할때마다 실행\r\n");
      out.write("					companySearch.addEventListener(\"keyup\", function(e){\r\n");
      out.write("						let value = e.target.value.trim();\r\n");
      out.write("						\r\n");
      out.write("						if(value !== \"\") {\r\n");
      out.write("							// 데이터를 /searchCompany 경로에 company라는 이름으로 보냄\r\n");
      out.write("							fetch(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/searchCompany?company=\" + encodeURIComponent(value))\r\n");
      out.write("							.then(response => response.json())\r\n");
      out.write("							.then(data => {\r\n");
      out.write("								console.log(data);\r\n");
      out.write("								companyDropdown.innerHTML = \"\"; // 기존 목록 비우기\r\n");
      out.write("								\r\n");
      out.write("								if(data && data.length > 0){\r\n");
      out.write("									companyDropdown.style.display = \"block\";\r\n");
      out.write("									\r\n");
      out.write("									data.forEach(item => {\r\n");
      out.write("										let btn = document.createElement(\"button\");\r\n");
      out.write("										btn.type = \"button\";\r\n");
      out.write("										btn.className = \"dropdown-item\";\r\n");
      out.write("										btn.textContent = item.companyName; // 보여줄 회사이름\r\n");
      out.write("										\r\n");
      out.write("										// 검색해서 나온 회사 이름 클릭\r\n");
      out.write("										btn.addEventListener(\"click\", function(){\r\n");
      out.write("											companySearch.value = item.companyName; // 회사이름 넣기\r\n");
      out.write("											comId.value = item.comId; // insert구문 실행위해 com_id 값 넣기\r\n");
      out.write("											companyDropdown.style.display = \"none\"; // 드롭다운 닫기\r\n");
      out.write("										});\r\n");
      out.write("										companyDropdown.appendChild(btn);\r\n");
      out.write("									});\r\n");
      out.write("								}\r\n");
      out.write("								else{ // 검색결과 없을때\r\n");
      out.write("									companyDropdown.innerHTML = \"<span class='dropdown-item text-muted disabled'>검색 결과가 없습니다.</span>\";\r\n");
      out.write("									companyDropdown.style.display = \"block\";\r\n");
      out.write("								}\r\n");
      out.write("							})\r\n");
      out.write("							.catch(error => {\r\n");
      out.write("								console.error(\"회사 검색 오류:\",error);\r\n");
      out.write("								companyDropdown.style.display = \"none\";\r\n");
      out.write("							});\r\n");
      out.write("						}\r\n");
      out.write("						else{ // 입력란 비어있을때 처리\r\n");
      out.write("							comId.value = \"\";\r\n");
      out.write("							companyDropdown.innerHTML = \"\";\r\n");
      out.write("							companyDropdown.style.display = \"none\";\r\n");
      out.write("							\r\n");
      out.write("						}\r\n");
      out.write("					});\r\n");
      out.write("					// 입력창 외부공간 클릭시 정리\r\n");
      out.write("					document.addEventListener(\"click\", function(e){\r\n");
      out.write("						if(e.target !== companySearch && e.target !== companyDropdown){\r\n");
      out.write("							companyDropdown.style.display = \"none\";\r\n");
      out.write("						}\r\n");
      out.write("					});\r\n");
      out.write("				});\r\n");
      out.write("				\r\n");
      out.write("				///////////////////// 회사 이름이랑 일치하는거 출력 /////////////////////\r\n");
      out.write("				\r\n");
      out.write("				/////////////////////// 검색해서 나온 데이터 전송 ///////////////////////\r\n");
      out.write("				\r\n");
      out.write("				function searchForm(page = 1){\r\n");
      out.write("					let comId = document.getElementById(\"comId\").value.trim();\r\n");
      out.write("					let forStatus = document.getElementById(\"forStatus\").value;\r\n");
      out.write("					let keyword = document.getElementById(\"keyword\").value;\r\n");
      out.write("					\r\n");
      out.write("					let url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/searchForms\"\r\n");
      out.write("							+ \"?keyword=\" + encodeURIComponent(keyword)\r\n");
      out.write("							+ \"&company=\" + comId\r\n");
      out.write("							+ \"&forStatus=\" + forStatus\r\n");
      out.write("					\r\n");
      out.write("					fetch(url)\r\n");
      out.write("					.then(response => response.json())\r\n");
      out.write("					.then(data => {\r\n");
      out.write("						console.log(data);\r\n");
      out.write("						updateTable(data);\r\n");
      out.write("					})\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				/////////////////////// 검색해서 나온 데이터 전송 ///////////////////////\r\n");
      out.write("								\r\n");
      out.write("				/////////////////////// 검색해서 나온 결과 출력 ///////////////////////\r\n");
      out.write("				\r\n");
      out.write("				function updateTable(data){\r\n");
      out.write("					// 출력할 공간\r\n");
      out.write("					let tbody = document.getElementById(\"formTbody\");\r\n");
      out.write("					\r\n");
      out.write("					tbody.innerHTML = \"\";\r\n");
      out.write("					\r\n");
      out.write("					if(data.length === 0){ // 없을때 출력할것\r\n");
      out.write("						tbody.innerHTML = \"<tr><td colspan='8' class='text-center'>검색 결과가 없습니다.</td></tr>\"\r\n");
      out.write("						return;\r\n");
      out.write("					}\r\n");
      out.write("					\r\n");
      out.write("					data.forEach((item, index) => {\r\n");
      out.write("						let tr = document.createElement(\"tr\"); // tr태그 생성\r\n");
      out.write("						\r\n");
      out.write("						let isActive = (item.forStatus === true);\r\n");
      out.write("						\r\n");
      out.write("						// 코드 더러워서 위에서 벳지 처리\r\n");
      out.write("						let badgeClass = isActive ? 'bg-success' : 'bg-secondary';\r\n");
      out.write("						let badgeText = isActive ? '활성화' : '비활성화'\r\n");
      out.write("\r\n");
      out.write("						tr.innerHTML = `\r\n");
      out.write("						<td>${index + 1}</td>\r\n");
      out.write("						<td><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/appr/update_form?forId=${item.forId}\">\r\n");
      out.write("						${item.forCode}</a></td>\r\n");
      out.write("						<td>${item.forTitle}</td>\r\n");
      out.write("						<td>${item.comName}</td>\r\n");
      out.write("						<td><span class=\"badge ${badgeClass}\">${badgeText}</span></td>\r\n");
      out.write("						<td>${item.forCreated}</td>\r\n");
      out.write("						<td>${item.forUpdated}</td>\r\n");
      out.write("						`;\r\n");
      out.write("						\r\n");
      out.write("						tbody.appendChild(tr); // 위 데이터 다 넣어서 보내기\r\n");
      out.write("					});\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				/////////////////////// 검색해서 나온 결과 출력 ///////////////////////\r\n");
      out.write("				\r\n");
      out.write("				/////////////////////////   페이징 기능    /////////////////////////\r\n");
      out.write("				\r\n");
      out.write("				function updatePaging(paging){\r\n");
      out.write("					const tfoot = document.getElementById(\"formTfoot\");\r\n");
      out.write("					\r\n");
      out.write("					let html = `<tr><td colspan=\"5\">`;\r\n");
      out.write("					html += `<ul class=\"pagination justify-content-center\">`;\r\n");
      out.write("					\r\n");
      out.write("					if(paging.start > 1){\r\n");
      out.write("						html += `\r\n");
      out.write("						<li class=\"page-item\">\r\n");
      out.write("							<a href=\"#\" class=\"page-link\"\r\n");
      out.write("							onclick=\"searchForm(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${paging.start-1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("); return false;\">이전</a>\r\n");
      out.write("						</li>`;\r\n");
      out.write("					}\r\n");
      out.write("					\r\n");
      out.write("					for (let i = paging.start; i <= paging.end; i++){\r\n");
      out.write("						let activeClass = (i == paging.current) ? \"active\" : \"\";\r\n");
      out.write("						\r\n");
      out.write("						html +=`\r\n");
      out.write("							<li class=\"page-item ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activeClass}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("								<a href=\"#\" class=\"page-link\" \r\n");
      out.write("								onclick=\"searchForm(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("); return false;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\r\n");
      out.write("						</li>`;\r\n");
      out.write("					}\r\n");
      out.write("					\r\n");
      out.write("					if(paging.end < paging.pagetotal){\r\n");
      out.write("						html += `\r\n");
      out.write("						<li class=\"page-item\">\r\n");
      out.write("							<a href=\"#\" class=\"page-link\"\r\n");
      out.write("							onclick=\"searchForm(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${paging.end +1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("); return false;\">다음</a>\r\n");
      out.write("						</li>`;\r\n");
      out.write("					}\r\n");
      out.write("					\r\n");
      out.write("					html += `</ul></td></tr>`;\r\n");
      out.write("					\r\n");
      out.write("					tfoot.innerHTML = html;	\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				/////////////////////////   페이징 기능    /////////////////////////\r\n");
      out.write("			</script>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"my-3\">	\r\n");
      out.write("				<label for=\"forStatus\" class=\"form-label fw-bold small text-secondary\">활성화 여부</label>\r\n");
      out.write("				\r\n");
      out.write("				<select class=\"form-select\" id=\"forStatus\" name=\"forStatus\">\r\n");
      out.write("					<option value=\"\" selected>전체</option>\r\n");
      out.write("					<option value=\"true\">활성화</option>\r\n");
      out.write("					<option value=\"false\">비활성화</option>\r\n");
      out.write("				</select>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"text-end\">\r\n");
      out.write("				<button type=\"reset\" class=\"btn btn-outline-primary\">초기화</button>\r\n");
      out.write("				<button type=\"button\" class=\"btn btn-primary\" onclick=\"searchForm()\">검색</button>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div>\r\n");
      out.write("		<table class=\"table  table-striped  table-bordered table-hover\">\r\n");
      out.write("			<caption>양식 목록</caption>\r\n");
      out.write("			<thead>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>번호</th>\r\n");
      out.write("					<th>양식 코드</th>\r\n");
      out.write("					<th>양식 제목</th>\r\n");
      out.write("					<th>회사</th>\r\n");
      out.write("					<th>사용 여부</th>\r\n");
      out.write("					<th>생성일</th>\r\n");
      out.write("					<th>수정일</th>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</thead>\r\n");
      out.write("			<tbody id=\"formTbody\">\r\n");
      out.write("			</tbody>\r\n");
      out.write("		</table>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
